### ISSUE TITLE
[Feat] MapKit Annotation을 통해 맵 위에 다양한 추가 정보를 보여줍니다.

### ISSUE THREAD

**Issue by hardworking-nomad** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#11]
### 작업할 내용

테스트 장소핀 등록하고, 핀의 디자인을 custom하고, 맵을 탐색할 때마다 핀들을 reuse하는데 모두 annotation이 쓰입니다.
내 위치 주변 Circle 그리기도 annotation 방식을 활용합니다.

### 관련 이슈넘버

#7

### 스크린샷 혹은 gif

<img width="300" alt="image" src="https://user-images.githubusercontent.com/103012800/196371505-00de3f93-a68c-41e5-8d4c-a9c7a58dc309.png">

### TODO

- [x] 테스트 장소 클래스에서 위치 정보, 이름 등 불러와서 핀으로 등록하고 지도 위에 띄우기
- [x] 핀 디자인 커스터마이즈
- [x] 내 위치 CoreLocation / MKUserLocation 중 하나로 불러오기
- [x] 내 위치를 중심으로 Circle Draw
- [ ] 실시간 위치 이동에 따라 Circle 이동, redraw
- [ ] 특정 장소가 Circle 영역 내에 들어왔는지 Boolean 판단
