### ISSUE TITLE
[Feat] 프로필 통계화면 만들기

### ISSUE THREAD

**Issue by heokyeol** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#14]
### 작업할 내용

프로필뷰 첫번째 네비게이션에서의 통계 뷰를 만든다.
이후 달력뷰에서 사용할 날자 데이터도 미리 구현
반응형 날자 인디케이터

### 관련 이슈넘버

#1

### TODO

- [x] 날자 포멧 만들기
- [x] 통계 주차 이동 버튼 만들기 및 기능구현
- [ ] 통계 목데이터 만들기
