### ISSUE TITLE
[Feat] LoginView UI에 Sign In with Apple 적용

### ISSUE THREAD

**Issue by eunbkang** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#15]
### 작업할 내용

애플로그인을 사용해서 로그인하는 화면을 구현하고자 합니다.
- 애플로그인 인증 창을 띄우기 위한 프로젝트 세팅 포함
- 인증 결과를 다루는 것은 추후 작업 예정

### 스크린샷 혹은 gif

<img src= "https://user-images.githubusercontent.com/103012157/196583127-7902548d-add6-49bf-9021-445b966ac35b.png" width = 300>

### TODO

- [x] LoginView UI 임시 로고로 만들기
- [x] 애플로그인 관련 프로젝트 세팅
- [x] 애플로그인 버튼 띄우기
- [x] 애플로그인 인증 창 띄우기

**Comment by sunshiningsoo** [comment]
#20 에서 머지완료
