### ISSUE TITLE
[Feat] 맵뷰 UI 변경 및 지역 변경 기능 구현

### ISSUE THREAD

**Issue by hardworking-nomad** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#165]
### 작업할 내용

새로운 맵 디자인에 따라 UI를 변경하고 지역 변경 기능을 구현합니다.

### 스크린샷 혹은 gif

<img width="300" alt="image" src="https://user-images.githubusercontent.com/103012800/200257400-862ac624-41b5-40ba-89f2-8dca6515f321.png">

### TODO

- [ ] 좌측 상단에 지역명 표기
- [ ] 지역명 터치 시 지역 변경 모달 띄우기
  - [ ] 초기 런칭 시 띄울 지역 정하기
- [ ] 지역 선택 시 MapRegion 변경하기
- [ ] 프로필, 설정, 자기 위치로 가기, 리스트로보기 버튼 위치 및 디자인 변경
