### ISSUE TITLE
[Feat] SignUpView 디자인 수정

### ISSUE THREAD

**Issue by eunbkang** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#178]
### 작업할 내용

- 상태가 자기소개로 변경됨에 따라 textField를 textView로 수정하고 UI와 글자수 제한을 수정합니다.
- 사진 업로드하기 위한 UI를 업데이트합니다.
- 사진 업로드 단계가 추가됨에 따라 단계 dot, 상단 문구, 다음 버튼 등을 수정합니다.

### 관련 이슈넘버

#5

### 스크린샷 혹은 gif

<p align = "left">
<img width="300" alt="Screen Shot 2022-11-08 at 1 52 00 PM" src="https://user-images.githubusercontent.com/103012157/200478116-d0125a41-82c8-4a3f-b492-4c17e452b241.png">

<img width="300" alt="Screen Shot 2022-11-08 at 1 49 44 PM" src="https://user-images.githubusercontent.com/103012157/200477771-07d3cbcd-32a9-4b0b-a21f-2fb01695c45f.png">
</p>

### TODO

- [ ] 자기소개 입력란 UI, 카운터 수정
- [ ] 버튼 모양, 단계에 따른 문구 수정
- [ ] 네번째 입력 단계를 위한 상단 문구, dots 수정
- [ ] 사진 업로드 UI 만들기
