### ISSUE TITLE
[Feat] SettingView UI를 작업합니다.

### ISSUE THREAD

**Issue by sunshiningsoo** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#192]
### 작업할 내용

- MapViewController에서 톱니바퀴 버튼 클릭시 넘어가는 SettingView UI를 작성합니다.

### 관련 이슈넘버

nil

### 스크린샷 혹은 gif

<img width="765" alt="스크린샷 2022-11-10 12 33 18" src="https://user-images.githubusercontent.com/72736657/200994409-829329fc-88d7-41f8-b761-68f17dee1cc4.png">

프로필 편집의 경우에 ProfileView로 동작이 옮겨갔습니다.

### TODO

- [x] SettingView tableView로 만들기
- [x] 장소 제보 뷰 작성
- [x] 로그아웃 Alert
- [x] 회원탈퇴 확인 뷰 작성

**Comment by hardworking-nomad** [comment]
로그인 상태일때와 로그아웃 상태일 때 메뉴가 달라야 할 수도 있겠네요!
