### ISSUE TITLE
[Integrate] 현재까지의 UI 통합 및 간단한 기능을 작업합니다.

### ISSUE THREAD

**Issue by sunshiningsoo** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#218]
### 다 될지는 모르지만 일단 해야되는 checkList

- [x] UI 통합
- [x] CustomModal에서 체크인 되어 있는 업무공간이면 highlight해두기
- [x] 런치 스크린 이미지 바꾸기
- [x] 체크인 버튼 floating에서 cell안의 버튼으로 delegate 넣기
- [ ] PlaceInfoModal UINavigation안에 넣어서 뿌리기
- [ ] 체크인할때, textField 넣어서 작성 후 들어가게 만듬
- [x] 장소 제보, nil인 값 alert 추가
- [ ] 애플로그인 작동하게 만듬
- [x] 체크아웃 후 리뷰 작성 modal 나오게 만듬
- [ ] 다이나믹 height 어떻게 해야할지
- [ ] PlaceInfoView에서 어떤 곳을 클릭하더라도 Login하라는 모달이 뜨도록 만들어주어야 함
- [x] ClearSelectedAnnotation delegate 삭제

-> 하다보니까 Apple Login과 체크인 버튼 cell 안으로 옮기는게 제일 공사여씀,,,
-> 체크인 버튼 cell안으로 옮기고 작동하게 부터 하자..!

### 관련 이슈넘버

nil

### 스크린샷 혹은 gif

전체 Flow를 잡습니다.

### TODO

- 이후로 부족한 부분은 해당 페이지 담당하는 사람이 진행!
