### ISSUE TITLE
[Feat] 체크인 시 오늘의 목표를 기입하는 Text Field 를 추가합니다

### ISSUE THREAD

**Issue by hardworking-nomad** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#225]
### 작업할 내용

체크인할 때 Text Field 를 추가합니다.

### 스크린샷 혹은 gif

<img width="300" alt="image" src="https://user-images.githubusercontent.com/103012800/201577827-47420fc7-5927-4b02-be56-db14a04aa487.png">

### TODO

- [x] 체크인 alert 안에 text field 추가 : '오늘의 목표를 알려주세요'
- [x] text field 입력 안할 시 체크인 불가
- [ ] 체크인 관련 데이터모델 추가 -> tempMessage or checkInMessage

**Comment by sunshiningsoo** [comment]
#229 에서 머지완료
