### ISSUE TITLE
[Feat] PlaceCheckInView 프로그래스바 구현

### ISSUE THREAD

**Issue by eunbkang** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#226]
### 작업할 내용

체크인뷰의 체크아웃하기 버튼 위의 프로그래스바를 00:00 ~ 24:00로 바꾸고 체크인 시간부터 이용시간까지 표시되도록 작업합니다.

### 스크린샷 혹은 gif

<img width="300" alt="Screen Shot 2022-11-14 at 1 50 16 PM" src="https://user-images.githubusercontent.com/103012157/201577814-c78c447c-2e8b-4dbc-a516-5fc11885b703.png">

### TODO

- [x] Label 변경
- [x] 바에 체크인 시간 표시
- [x] 바에 현재시간 표시
- [x] 체크인 시간 ~ 현재시간 사이 하이라이트

**Comment by sunshiningsoo** [comment]
#228 머지완료
