### ISSUE TITLE
[Feat] 내가 방문했던 장소, 체크인 했던 장소의 핀만 볼 수 있도록 필터(토글?)를 구현합니다.

### ISSUE THREAD

**Issue by hardworking-nomad** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#230]
### 작업할 내용

맵 위에 내가 방문했던 장소의 핀만 뜨도록 필터를 구현합니다.

### TODO

- [ ] combine으로 가져오는 places와 user의 checkInHistory 장소 정보를 비교해서 방문했던 장소만 가져오기
- [ ] 맵 annotation 모두 제거 후 방문했던 장소만 annotation 다시 추가
- [ ] 토글 or filter 버튼으로 해당 액션 연결
