### ISSUE TITLE
[Feat]PlaceInfoModal내 UI디자인 변경 점 적용

### ISSUE THREAD

**Issue by Willowwryu** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#233]
### 작업할 내용

- OperatingTime 디자인 변경점 적용

### 스크린샷 혹은 gif

<img width="288" alt="스크린샷 2022-11-15 오전 9 14 31" src="https://user-images.githubusercontent.com/103012086/201794887-8505348a-8a50-490f-8827-6c5a580102f9.png">

### TODO

- [x] 확장버튼 및 확장정보 표시 삭제
- [x] 정보 표시 방법 변경
- [x]  영업중 레이블 삭제
