### ISSUE TITLE
[Feat]리뷰 인포 셀 ui디자인 수정, 데이터 바인딩

### ISSUE THREAD

**Issue by Willowwryu** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#235]
### 작업할 내용

- PlaceInfoModal의 ReviewInfoCell의 데이터 바인딩 후 잘 맞지 않는 UI수정
- 리뷰 개수 데이터 바인딩 작업

### 스크린샷 혹은 gif

<img width="300" alt="스크린샷 2022-11-15 오전 9 57 33" src="https://user-images.githubusercontent.com/103012086/201800468-5d23d73b-085d-4c5f-aceb-ed14c3dfc022.png">

### TODO

- [x] horizontal 디바이더 오토레이아웃 수치 조정
- [x] 방문자 수 .count 데이터 바인딩
- [x] 프로필사진 radius 적용
- [x] 전체리뷰 보기 구현
