### ISSUE TITLE
[Enhancement] SignUpView 업데이트

### ISSUE THREAD

**Issue by eunbkang** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#236]
### 작업할 내용

- 닉네임, 직업, 자기소개 작성 후 사진 업로드는 별도 화면에서 하도록 함
- 회원가입 중 나갈 수 있도록 우측 상단 취소 버튼 & Alert(정말 취소하시겠습니까) 추가

### 관련 이슈넘버

#178

### 스크린샷 혹은 gif

<img width="594" alt="Screen Shot 2022-11-15 at 11 10 11 AM" src="https://user-images.githubusercontent.com/103012157/201809267-b29de45c-1179-40c5-8042-3ae6ee9c9bf2.png">

### TODO

- [x] 사진 업로드 뷰 생성 및 UI 작업
- [x] 자기소개 입력 후 다음 버튼 누르면 사진 업로드 뷰로 이동
- [x] 사진 업로드 뷰에서 완료 누르면 닫히기
- [x] 우측 상단에 회원가입 취소 버튼 & Alert 추가

**Comment by sunshiningsoo** [comment]
close #241
