### ISSUE TITLE
[Feat] 체크인 상태에서 맵뷰 상단에 띄울 체크인 카드(?) 를 구현합니다

### ISSUE THREAD

**Issue by hardworking-nomad** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#253]
### 작업할 내용

체크인 상태에서 체크인 상태라는 걸 맵뷰에서 더 본격적으로 알려주고, 체크인 뷰로 넘어가기 쉽도록 수정합니다.
기존 : '업무중' 버튼 하나
수정 : 체크인 카드를 만들어 우측 상단에 띄우기 + alpha 값이 적용된 상단 바의 색상을 white 에서 nomad blue 로 바꿔서 status 가 달라졌음을 직관적으로 전달

### 스크린샷 혹은 gif

<img width="206" alt="image" src="https://user-images.githubusercontent.com/103012800/202356222-2724f458-afba-423f-bc3e-d89f6b21045d.png">

### TODO

- [x] 체크인 카드 만들기
- [x] 체크인 여부에 따라 맵 뷰에 카드 추가
- [x] 체크인 여부에 따라 맵 뷰 상단 status bar 부분 색상 변경
- [x] 체크인 카드 클릭 시 placeCheckInView로 연결 (기존 업무중 클릭 시 연결과 동일)
- [x] 체크인 상태에서 체크인 된 장소 모달을 볼 때 '체크아웃' 버튼 -> '현재 이 장소에 체크인 중' 버튼으로 변경
- [x] '현재 이 장소에 체크인 중' 버튼 클릭 시 placeCheckInView로 연결
