### ISSUE TITLE
[Enhancement] 체크인 되어있는 상태로 로그아웃, 회원탈퇴 -> 자동 체크아웃, 퀘스트 나옴 +세팅뷰 오류 수정

### ISSUE THREAD

**Issue by sunshiningsoo** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#257]
### 작업할 내용

- 체크인 되어있는 상태로 로그아웃 혹은 회원 탈퇴 액션을 했을때, 자동으로 속한 장소에서 체크아웃을 하고, 참여한 퀘스트가 있다면 퀘스트에서 나오게 만듭니다.
- 추가로 세팅뷰에서 나오다가 들어갔을때, NavigationBar가 사라지는 오류를 고칩니다.

### 관련 이슈넘버

#224

### 고려할 점
- setCheckOut 액션시, checkInHistory의 lastIndex인지 firstIndex인지 맞추어야 할듯
- ~~setCheckOut or withdraw 액션시, 퀘스트를 지워버리면, 참여한 모든 사람의 퀘스트 참여 여부를 지워주어야 함~~
    - ~~자신이 organizer인 경우, 퀘스트를 지워버리고, 퀘스트에 속한 사람들의 퀘스트 참여여부를 다 지움~~
    - ~~자신이 organizer가 아닌 경우, 참석한 퀘스트들에서 나감~~

- 체크인 혹은 밋업에 속해 있을때, 로그아웃 or 회원탈퇴를 하는 경우
     - alert 메시지에 체크 아웃으로 바뀌고, 밋업에서 빠짐을 명시하고
     - 유저는 체크아웃 상태로, organizer와 상관없이 밋업에서 빠짐

### TODO

- [x] 체크인 되어있는지 check
- [x] 로그아웃시, 체크아웃과 퀘스트 나오기
- [x] 회원탈퇴시, 체크아웃과 퀘스트 나오기
- [x] SettingViewController NavigationBar 수정
