### ISSUE TITLE
[Feat] PlaceCheckInView에 데이터 불러오기

### ISSUE THREAD

**Issue by YeeunKim-archive** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#27]
### 작업할 내용

* PlaceCheckInView 상단 사용자 정보(UserProfile) 및 해당 공간 정보(Place) 표시 
* DummyData 활용 예정

### 관련 이슈넘버

#6

### 스크린샷 혹은 gif

<img src = "https://user-images.githubusercontent.com/95920991/197058094-34b403ca-7c5e-4bfa-a095-7870da192a35.png" width = 300>

### TODO

- [ ] DummyData에서 유저 정보 불러오기 
- [ ] DummyData에서 공간 정보 불러오기 
- [ ] 지도핀 정보 '제주시' -> '포항시' 로 변경

**Comment by sunshiningsoo** [comment]
@eunbkang #47 UI 작업중!

해당 이슈 close
