### ISSUE TITLE
[Bug] PlaceInfoView 버그 픽스

### ISSUE THREAD

**Issue by Willowwryu** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#298]
### 작업할 내용

- 1차 배포 이후 생기거나 발견 못 한 뷰 내에 버그픽스

### TODO

- [ ] 위치 정보 없을 때 장소 정보 데이터 바인딩 실패 수정
- [x] 주소 정보 줄바꿈
- [ ] #300
- [x] 밋업 갯수 바인딩 변경
