### ISSUE TITLE
[Feat] 체크인 한 장소에서 500m 이상 멀어지면 자동 체크아웃

### ISSUE THREAD

**Issue by hardworking-nomad** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#314]
### 작업할 내용

- 체크인 후 주기적으로 체크인 한 장소와 유저 로케이션의 거리를 측정하여 500m 이상 멀어지면 자동으로 체크아웃 구현
- 체크아웃 처리를 하면 유저가 앱을 켰을 때 메시지를 띄워 체크아웃 되었음을 알림 (알릴 수 있을지? 일단 시도)

### TODO

- [ ] 500미터 거리 계산을 주기적으로 실행 (5분 간격? 10분 간격?)
- [ ] 500미터 이상 범위 벗어날 시 자동 체크아웃
- [ ] 자동 체크아웃 된 후 앱을 실행할 때 메시지 노출 (일반적인 체크인/체크아웃과 자동 체크아웃을 별도로 체크할 수 있을지?)
