### ISSUE TITLE
[Feat] 수정된 PlaceCheckInView의 상단 카드 UI

### ISSUE THREAD

**Issue by eunbkang** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#47]
### 작업할 내용

- 체크인 후 나오는 뷰가 체크아웃 버튼과 이용시간이 포함된 뷰로 수정되었습니다.
- 바뀐 상단의 체크인 카드의 UI를 작업하고자 합니다.

### 스크린샷 혹은 gif

<img width="300" alt="Screen Shot 2022-10-24 at 5 20 08 PM" src="https://user-images.githubusercontent.com/103012157/197480551-450420af-5ac6-4655-b6e0-3a3ad324c954.png">

### TODO

- [x] 기존 코드 스터디
- [x] 전체적으로 UI 그리기
- [x] 그래프 그리기
- [x] 체크아웃 버튼 연결
