### ISSUE TITLE
[Setting] project에 주입되어 있는 Sign in with Apple을 삭제합니다.

### ISSUE THREAD

**Issue by sunshiningsoo** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#49]
### 작업할 내용

- 프로젝트 파일에 주입되어 있는 Sign up with Apple Login 기능을 삭제 합니다.
- 데이터가 들어오기 전 UI 마무리 작업을 한 이후에 진행할 예정입니다.

### 관련 이슈넘버

nil

### 스크린샷 혹은 gif

nil

### TODO

- [ ] Project - Target에서 삭제, 
- [ ] BNomad.entitlements 삭제
- [ ] Team 본인으로 설정해도 빌드와 실행이 되도록 확인
