### ISSUE TITLE
[Feat] SignUpView UI 작업

### ISSUE THREAD

**Issue by eunbkang** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#5]
### SignUpView UI 그리기
- 닉네임, 직업, 상태 메시지를 입력받는 화면입니다.
- 닉네임 입력 완료하면 직업 입력 칸이 나오고, 직업 입력 완료하면 상태 메시지 입력 칸이 나옵니다.
- 입력 단계에 따라 상단 문구와 단계 표시가 바뀝니다.
- 사용자의 입력 칸 선택에 따라 TextField 밑줄 색상을 바꿉니다.

### 스크린샷 혹은 gif

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/103012157/196312015-5f9693bc-174b-45a2-b619-9be546922539.png">

### TODO

- [x] 전체적으로 UI 만들기
- [x] 한 칸 입력 확인에 따라 상단 문구 바꾸기
- [x] 한 칸 입력 확인에 따라 다음 입력 칸 나오게 하기
- [x] 한 칸 입력 확인에 따라 단계 표시 바뀌게 하기
- [x] TextField 선택에 따라 밑줄 색상 바뀌게 하기
