### ISSUE TITLE
[Feat] SignUpView 입력받은 정보로 user 생성 및 firebase에 업데이트

### ISSUE THREAD

**Issue by eunbkang** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#63]
### 작업할 내용

회원가입 시 입력받은 정보(닉네임, 직업, 매시지)로 user 생성하고 firebase에도 업데이트하는 작업입니다.
+ 글자수 제한하는 기능과 화면 빈 곳 터치 시 키보드 내려가는 기능도 함께 추가하겠습니다.

### TODO

- [x] 입력받은 정보(닉네임, 직업, 메시지)로 user 생성
- [x] 생성된 user를 firebase에 업데이트
- [x] 입력받는 글자수 제한
- [x] 화면 빈 곳 터치하면 키보드 내리기
