### ISSUE TITLE
[Feat] 프로필뷰 하드코딩 수정 및 체크인 데이터 로직 구현

### ISSUE THREAD

**Issue by heokyeol** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#64]
### 작업할 내용

프로필뷰와 프로필 에디터 뷰의 하드코딩 데이터를 파이어베이스 데이터 형식으로 수정합니다.
캘린더뷰와 캘린더뷰셀 사이 데이터 구조를 만들고 로직을 짭니다.

### TODO
- [x] 프로필뷰 컬렉션뷰 셀프프로필 셀 데이터 연결
- [ ] 프로필뷰 컬렉션뷰 비지트카드 셀 데이터 연결
- [ ] 캘린더뷰 도장찍기 데이터 연결
- [ ] 캘린더뷰 비짓카드 개수 데이터 연결
- [ ] 캘린더뷰 비짓카드 내용 데이터 연결
