### ISSUE TITLE
[Feat] 맵뷰 관련 데이터 연결 및 비동기 처리

### ISSUE THREAD

**Issue by hardworking-nomad** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#66]
### 작업할 내용

더미데이터로부터 유저 및 장소 정보를 불러와 연결하고, 비동기처리를 구현합니다.

### TODO

- [x] Firebase, 더미데이터 연결
- [x] isLogin 판별 후 프로필 화면 연결
- [ ] PlaceAnnotation nil값 대응
