### ISSUE TITLE
[Feat] 앱에 지도를 띄우고 현재 자신의 위치를 표시하고 기본 버튼을 배치합니다.

### ISSUE THREAD

**Issue by hardworking-nomad** [DeveloperAcademy-POSTECH/MacC-Team-NoPower#7]
### 작업할 내용

앱 시작 시 제일 처음 보이는 지도 화면을 생성하고 상세 설정을 조정합니다.
기본 버튼은 자리만 잡아 놓고 뷰 연결은 나중에 합니다. (프로필, 세팅)
지도에 핀을 표시하고 한 화면 내에 보이는 장소들을 목록으로 보여주거나 (모달) 핀 각각의 장소 디테일뷰를 띄우는 작업 (모달) 은 별도 이슈로 생성하겠습니다.

### 스크린샷 혹은 gif

<img width="300" alt="image" src="https://user-images.githubusercontent.com/103012800/196312718-315de95c-ba30-4695-9a16-40b6f0afcc3b.png">

### TODO

- [x] 맵 생성
- [x] 맵 회전 시 나침반 노출 (북쪽으로 위치 맞추면 사라짐)
- [x] 프로필, 설정 버튼 생성 (Stack View, 뷰 연결은 나중에)
- [x] User Tracking 버튼 생성
- [x] 앱 시작 시 user location 확인 -> 지도 center를 user location으로 맞추기 -> span 설정으로 적당한 지도 축척으로 시작
- [ ] 자기 위치 중심으로 반경 000m 인식 및 표기
